openai_api_key: "place-holder"
google_credentials: "credentials.json"

drive_folder_ids:
  pdf: "1YrYWjpWUmGN-ISJK0TrO66SirBsLeMcH"
  doc: "1Ja_3axmjpBO0pTImZiGNFF4qEtgPt50z"
  csv: "1YrYWjpWUmGN-ISJK0TrO66SirBsLeMcH"

template_sheet_id: "1jz-1gNw5hEEhKgq28v7G8dkdaNcBIw2UjLjCkgAskhp7w3VFkdu_7_QZ"

regex_patterns:
  style_number: "\\b(DZ\\d{2}[A-Z]\\d{3,5}(-SET|-D)?|HF\\d{2}[A-Z]\\d{3,5}(-SET|-D)?)\\b"

apps_script:
  template_id: "1TPhLZs6kVTAvrSdwz1felrAq8c1Bd1xxfC-Z9-DAP2k"  # ID of your master Google Sheet with script
  timezone: "America/Los_Angeles"

