openai_api_key: "place-holder"
google_credentials: "credentials.json"

drive_folder_ids:
  pdf: "1YrYWjpWUmGN-ISJK0TrO66SirBsLeMcH"
  doc: "1Ja_3axmjpBO0pTImZiGNFF4qEtgPt50z"
  csv: "1YrYWjpWUmGN-ISJK0TrO66SirBsLeMcH"

template_sheet_id: "1MgmD0ncx7GmtmEaxQmhs8m_bi-1TBGeX8q4cixcFiF4"

regex_patterns:
  style_number: "\\b(DZ\\d{2}[A-Z]\\d{3,5}(-SET|-D)?|HF\\d{2}[A-Z]\\d{3,5}(-SET|-D)?)\\b"

apps_script:
  template_sheet_id: "1MgmD0ncx7GmtmEaxQmhs8m_bi-1TBGeX8q4cixcFiF4"
  timezone: "America/Los_Angeles"

