name: Run AI Agent Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Start from a clean environment
        run: |
          pip uninstall -y openai || true
          pip uninstall -y clip || true
          pip cache purge
          rm -rf ~/.cache/pip

      - name: Install all requirements (excluding openai)
        run: |
          pip install -r requirements.txt --no-deps || true
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Reinstall correct OpenAI version last
        run: pip install --force-reinstall openai==1.13.3

      - name: Check OpenAI version (must be 1.13.3)
        run: pip show openai

      - name: Create data directory
        run: mkdir -p data

      - name: Run main.py on all local PDFs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "Starting AI agent run..."
          for file in *.pdf; do
            echo "Processing $file"
            python main.py "$file"
          done

      - name: Confirm OpenAI SDK runtime details
        run: |
          python -c "import openai; print('✅ OpenAI version:', openai.__version__); print('✅ OpenAI path:', openai.__file__)"

    
