name: Run AI Agent Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggers

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      # ✅ Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ✅ Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      # ✅ (Optional) Create data directory
      - name: Create data directory
        run: mkdir -p data

      # ✅ Run Description Generator
      - name: Run main.py on all local PDFs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "Starting AI agent run..."
          for file in *.pdf; do
            echo "Processing $file"
            python main.py "$file"
          done

      # ✅ Run the QA Agent script
      - name: Run QA Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running QA optimization agent..."
          python QA_Agent.yaml
