name: Run AI Agent Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      # ✅ Check out your code
      - uses: actions/checkout@v3

      # ✅ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ✅ Install all dependencies in one place, force OpenAI version last
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          pip install --force-reinstall openai==1.13.3

      # ✅ Debug OpenAI version
      - name: Check OpenAI SDK version
        run: pip show openai

      # ✅ Create data directory
      - name: Create data directory
        run: mkdir -p data

      # ✅ Run main.py
      - name: Run main.py on all local PDFs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "Starting AI agent run..."
          for file in *.pdf; do
            echo "Processing $file"
            python main.py "$file"
          done

      # ✅ Run QA Agent
      - name: Run QA Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running QA optimization agent..."
          python qa_agent.py
