name: Run AI Agent Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clean pip and remove corrupted OpenAI SDK
        run: |
          pip uninstall -y openai clip httpx urllib3 || true
          pip cache purge
          rm -rf ~/.cache/pip
          rm -rf /opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/openai*

      - name: Install all other requirements
        run: |
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Install correct OpenAI SDK (last to avoid override)
        run: pip install --force-reinstall openai==1.13.3

      - name: Confirm OpenAI version
        run: |
          python -c "import openai; print('✅ OpenAI version:', openai.__version__); print('✅ OpenAI path:', openai.__file__)"

      - name: Create data directory
        run: mkdir -p data

      - name: Run main.py on all local PDFs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "Starting AI agent run..."
          for file in *.pdf; do
            echo "Processing $file"
            python main.py "$file"
          done
