name: Run AI Agent Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggers

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      # Check out your code
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # (Optional) Create a data directory if your code expects it
      - name: Create data directory
        run: mkdir -p data
           
      # Run the script
      - name: Run script on all PDFs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          for file in *.pdf; do
            echo "Processing $file"
            python main.py "$file"
          done
